# Generated by Django 5.2.8 on 2025-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id_number',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(),
        ),
    ]
